name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3.5.2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.2

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run ci:test

            - name: Upload test report
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: test-report.txt
                  path: test-report.txt

            - name: Run ESlint
              uses: npm run ci:lint || exit 0

            - name: Upload lint report
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: eslint-report.html
                  path: eslint-report.html
